pipeline {
    agent {
        docker {
            image 'gradle:8.6-jdk17' // You can update to the Gradle + JDK version you need
            args '-v $HOME/.gradle:/home/gradle/.gradle' // Optional: Caches Gradle for speed
        }
    }
    environment {
        DOCKER_IMAGE = "gauravcap01/user-service"
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/gauravcap01/springboot_microservice_gradle_project_with_docker_jenkins_k8s'
            }
        }
        stage('Build') {
            steps {
                sh 'gradle build -x test'
            }
        }
        stage('Test') {
            steps {
                sh 'gradle test'
            }
        }
        stage('Docker Build & Push') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}:${BUILD_NUMBER}").push()
                }
            }
        }
        stage('Ansible Deploy') {
            steps {
                sh 'ansible-playbook ansible/deploy.yml'
            }
        }
    }
}
