---
- name: Deploy app with Docker
  hosts: app_servers
  become: yes
  tasks:
    - name: Pull Docker image
      docker_image:
        name: your-dockerhub-username/app
        source: pull

    - name: Run container
      docker_container:
        name: springboot-ms
        image: your-dockerhub-username/app
        ports:
          - "8080:8080"
        state: started
