---
- name: Deploy app with Docker
  hosts: app_servers
  become: yes
  tasks:
    - name: Pull Docker image
      docker_image:
        name: gauravcap01/app
        source: pull

    - name: Run container
      docker_container:
        name: user-service-ms
        image: gauravcap01/app
        ports:
          - "8080:8080"
        state: started
